### ISSUE TITLE
3.18 support

### ISSUE THREAD

**Issue by varemenos** [gfxmonk/gnome-shell-scroll-workspaces#17]
Please add support for the new release

**Comment by varemenos** [comment]
Seems like there is already a commit that adds support for 3.18. Is it blocked from releasing by the Gnome team that reviews the extensions?

**Comment by gfxmonk** [comment]
I haven't uploaded the latest release yet. I'll try and get to it tonight.

**Comment by gfxmonk** [comment]
It's now in review.

**Comment by gfxmonk** [comment]
All done :+1:
